--- 
- name: email_from
  scope: user
  id: 1
  value: Unconfigured User <nobody@localhost>
- name: email_from
  scope: office
  id: 2
  value: Unconfigured User <nobody@localhost>
- name: ssl
  scope: payment
  id: 3
  value: true
  basic_type: boolean
- name: email_to
  scope: office
  id: 4
  value: nobody@localhost
- name: tax_rates
  scope: payment
  id: 5
  basic_type: hash
  value: {}

- name: thumbnail_width
  scope: image
  id: 6
  value: 120
  basic_type: integer
- name: thumbnail_height
  scope: image
  id: 7
  value: 300
  basic_type: integer
- name: thumbnail_exact_dimensions
  scope: image
  id: 8
  value: 0
  basic_type: boolean
- name: exact_dimensions
  scope: image
  id: 9
  value: 0
  basic_type: boolean
- name: width
  scope: image
  id: 10
  value: 240
  basic_type: integer
- name: height
  scope: image
  id: 11
  value: 600
  basic_type: integer
- name: missing_thumbnail
  scope: image
  id: 12
  value: /images/cart/t-notfound.gif
- name: missing_thumbnail_alt
  scope: image
  id: 13
  value: image coming soon
- name: products_per_page
  scope: office
  id: 14
  value: 20
  basic_type: integer
- name: quantity_warning_threshold
  id: 15
  value: 3
  basic_type: integer
- name: ship_to_canada
  scope: payment
  id: 16
  value: 
  basic_type: boolean
- name: default_product_weight
  scope: errors
  id: 17
  value: 5
  basic_type: integer
- name: products_per_page
  scope: store
  id: 18
  value: 20
  basic_type: integer
- name: product_reclaim_hours
  scope: cleanup
  id: 19
  value: 4
  basic_type: integer
- name: payment_clear_minutes
  scope: cleanup
  id: 20
  basic_type: integer
- name: omit_shipping_from_tax
  scope: payment
  id: 21
  value: 1
  basic_type: boolean
- name: auth_only
  scope: payment
  id: 22
  value: 
  basic_type: boolean
- name: disabled
  scope: coupons
  value: false
  basic_type: boolean
- name: allow_only_one
  scope: coupons
  value: true
  basic_type: boolean
